#!/bin/bash

source dwmconfig

case $BUTTON in
	1) pacupdatecheck &;;
esac

updates="$(cat ${XDG_DATA_HOME:-$HOME/.local/share}/updates)"
if [ "$COLORED" = true ]; then
	pgrep -x pacupdatecheck >/dev/null && icon=" 🔄"
	echo " 📦 $updates$icon |"
else
	# pgrep -x pacupdatecheck >/dev/null && icon=" $(cl 'gr' '')󰑓^d^"
	# pgrep -x pacupdatecheck >/dev/null && icon=" 󰑓"
	pgrep -x pacupdatecheck >/dev/null && icon=" (*)"
	# echo " 󰬦 $updates$icon  "
	echo " $(cl 'bl' '')Updates$icon: $(cl 'wh' '')$updates "
fi
