#!/bin/bash

[ -z "$SUCKENV_SRC" ] && SUCKENV_SRC="$HOME/.local/src/suckenv"
[ ! -d "$SUCKENV_SRC" ] && exit

themes="$(find "$SUCKENV_SRC"/themes -maxdepth 1 -type f | sed '/colors.h/d; s/.h$//')"
names=$(basename -a $themes)

echo "Select theme:"
sel=$(echo "$names" | fzf)
[ -z "$sel" ] && exit

echo "Changing dwm colorscheme..."
echo "Changing dmenu colorscheme..."
echo "Changing st colorscheme..."
echo "#include \"$sel.h\"" > "$SUCKENV_SRC"/themes/colors.h
cd "$SUCKENV_SRC" && sudo make install &>/dev/null

alac_col="${XDG_CONFIG_HOME:-$HOME/.config}/alacritty/colors.yml"
if [ -f $alac_col ]; then
	echo "Changing alacritty colorscheme..."
	sed -i "s/^colors: \*\S\+$/colors: *$sel/" $alac_col
fi

rofi_col="${XDG_CONFIG_HOME:-$HOME/.config}/rofi/themes/colors.rasi"
if [ -f $rofi_col ]; then
	echo "Changing rofi colorscheme..."
	echo "@import \"../styles/$sel.rasi\"" > $rofi_col
fi

zath_col="${XDG_CONFIG_HOME:-$HOME/.config}/zathura/zathurarc"
if [ -f $zath_col ]; then
	echo "Changing zathura colorscheme..."
	sed -i "s/^\s*include\s\S\+$/include $sel/" $zath_col
fi

if [ "$?" -eq 0 ]; then
	echo "Suckenv's theme changed to '$sel'"
	echo "Restart 'dwm' to see the changes"
else
	echo "An error has ocurred"
	echo "Suckenv's theme hasn't changed"
fi
